---
abstract: 'Configure your application to redirect all incoming requests to HTTPS'
author:
  - 'Natal Ngétal'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-SSLify
requires:
  Dancer: 0
  Dancer::Plugin: 0
  strict: 0
  warnings: 0
version: 0.121330
